import { siteImages } from "@/lib/site-images";

export const ZERO_LIQUID_DISCHARGE_SYSTEM = {
  title: "Zero Liquid Discharge Plant",
  intro:
    "A zero liquid discharge (ZLD) system is a water treatment process that aims to eliminate all liquid waste by treating and recycling all wastewater, leaving only solid waste. ZLD systems employ advanced technologies such as membrane filtration, evaporation, and crystallization to achieve complete water recovery and environmental compliance.",
  heroImages: {
    main: siteImages.smartCity,
    secondary: [siteImages.waterTreatmentB, siteImages.iot],
  },
  valueProposition:
    "ZLD systems employ the most advanced wastewater treatment technologies to purify and recycle.",
  valueImages: [siteImages.engineers, siteImages.etp],
  detailBlocks: [
    {
      num: "01",
      title: "Process Overview",
      body: "The ZLD process typically includes pre-treatment, membrane filtration such as reverse osmosis to concentrate the wastewater, and thermal treatment using evaporators and crystallizers. The goal is to recover maximum water while converting dissolved solids into dry cake or crystals for safe disposal.",
    },
    {
      num: "02",
      title: "Working",
      body: "Wastewater first undergoes pre-treatment to remove suspended solids and organics. Concentration is achieved using reverse osmosis or other membrane systems to reduce liquid volume. The remaining brine is treated in evaporators and crystallizers, where water is recovered as distillate and solids are separated. The recovered water can be reused in the plant, achieving near-zero liquid discharge.",
    },
    {
      num: "03",
      title: "Features",
      bullets: [
        "Energy efficient",
        "Cost-effective",
        "High-quality recycled water",
        "Minimal environmental impact",
        "Easy maintenance",
      ],
    },
    {
      num: "04",
      title: "Applications",
      bullets: [
        "Power plants and chemical plants",
        "Textile and food processing industries",
        "Sugar industries",
        "Oil and gas industries",
        "Pulp and paper industries",
      ],
    },
  ],
  faqs: [
    {
      question: "What is a Zero Liquid Discharge System (ZLD) and what is it used for?",
      answer:
        "A ZLD system is designed to treat industrial wastewater so that no liquid effluent is discharged to the environment. All water is recovered for reuse and only solid waste remains, helping industries meet strict pollution control norms and sustainability goals.",
    },
    {
      question: "How does a ZLD system work?",
      answer:
        "ZLD works through pre-treatment, membrane concentration (RO/NF), and thermal evaporation/crystallization. Wastewater is progressively concentrated until solids precipitate and water is recovered as high-purity distillate for reuse.",
    },
    {
      question: "What are the benefits of using a ZLD system?",
      answer:
        "Benefits include elimination of liquid discharge, water reuse, regulatory compliance, reduced freshwater consumption, protection of ecosystems, and improved corporate environmental responsibility.",
    },
    {
      question: "Which industries most commonly use ZLD systems?",
      answer:
        "ZLD is widely used in power generation, chemicals, pharmaceuticals, textiles, food and beverage, sugar, oil and gas, pulp and paper, and electroplating industries where discharge norms are stringent.",
    },
    {
      question: "What is the typical treatment process for a ZLD system?",
      answer:
        "Typical stages include equalization, pre-treatment, biological or chemical treatment if needed, membrane filtration (UF/RO), evaporators, crystallizers, and solids handling for landfill or beneficial use.",
    },
    {
      question: "How is a ZLD system maintained?",
      answer:
        "Maintenance includes monitoring membrane performance, cleaning evaporators, inspecting pumps and heat exchangers, managing chemical dosing, periodic descaling, and safe handling of generated solid waste per regulatory guidelines.",
    },
    {
      question: "Does a ZLD system ensure high energy consumption?",
      answer:
        "Thermal evaporation stages are energy-intensive, but modern ZLD plants use energy recovery devices, optimized process design, and hybrid configurations to reduce overall operating costs compared to older systems.",
    },
    {
      question: "How can we ensure the safe disposal of the solid waste generated by a ZLD system?",
      answer:
        "Solid waste should be characterized, stabilized if required, and disposed of at authorized facilities or reused where permitted. KHM provides guidance on sludge/salt cake handling in compliance with local pollution control board requirements.",
    },
  ],
} as const;
